# Generated by Django 3.0.5 on 2021-06-02 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Umarsafarisrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rooms', models.CharField(choices=[('DEL', (('DL1', 'D1'), ('DL2', 'D2'))), ('Rook', 'RK1'), ('Bishop', 'BP1'), ('Castle', 'CST1')], default='room', max_length=10)),
                ('Beds', models.CharField(default=0, max_length=1)),
                ('Description', models.TextField()),
                ('Photo1', models.ImageField(default='default.jpg', upload_to='apartments')),
                ('Photo2', models.ImageField(default='default.jpg', upload_to='apartments')),
                ('Photo3', models.ImageField(default='default.jpg', upload_to='apartments')),
                ('Photo4', models.ImageField(default='default.jpg', upload_to='apartments')),
                ('Photo5', models.ImageField(default='default.jpg', upload_to='apartments')),
                ('slug', models.SlugField(default='0')),
            ],
            options={
                'verbose_name_plural': 'Posted UmarSafaris Apartments ',
            },
        ),
        migrations.CreateModel(
            name='Booking_ApartmentsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('ID_No', models.CharField(max_length=30)),
                ('Tel', models.CharField(max_length=13)),
                ('Check_In', models.DateField(default=django.utils.timezone.now)),
                ('Check_In_Time', models.TimeField(default=django.utils.timezone.now)),
                ('Check_Out', models.DateField(default=django.utils.timezone.now)),
                ('Check_Out_Time', models.TimeField(default=django.utils.timezone.now)),
                ('Apartment', models.ForeignKey(choices=[('DEL', (('DL1', 'D1'), ('DL2', 'D2'))), ('Rook', 'RK1'), ('Bishop', 'BP1'), ('Castle', 'CST1')], on_delete=django.db.models.deletion.CASCADE, to='apartment.Umarsafarisrooms')),
            ],
            options={
                'verbose_name_plural': ' Apartment Clients Booking Information',
            },
        ),
    ]
