# Generated by Django 3.0.5 on 2021-06-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_umarsafarisrooms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_apartmentsform',
            name='Apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Umarsafarisrooms'),
        ),
    ]
