# Generated by Django 3.0.5 on 2021-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20210602_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umarsafarisrooms',
            name='Rooms',
            field=models.CharField(choices=[('DEL', (('DL1', 'D1'), ('DL2', 'D2'), ('DL3', 'D3'), ('DL4', 'D4'))), ('Rook', (('RK1', 'RK1'), ('RK2', 'RK2'), ('RK3', 'RK3'), ('RK4', 'RK4'))), ('Bishop', (('BSP1', 'BSP1'), ('BSP2', 'BSP2'), ('BSP3', 'BSP3'), ('BSP4', 'BSP4'))), ('Castle', (('CST1', 'CST1'), ('CST2', 'CST2'), ('CST3', 'CST3'), ('CST4', 'CST4')))], default='room', max_length=10),
        ),
    ]
