# Generated by Django 3.0.5 on 2021-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_auto_20210603_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='umarsafarisrooms',
            name='Room_details',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
