# Generated by Django 3.0.5 on 2021-06-02 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_caruser_booking',
            name='Booking_from',
        ),
        migrations.RemoveField(
            model_name='current_caruser_booking',
            name='Booking_to',
        ),
        migrations.AddField(
            model_name='current_caruser_booking',
            name='Check_In',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_caruser_booking',
            name='Check_In_Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_caruser_booking',
            name='Check_Out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_caruser_booking',
            name='Check_Out_Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cars_available',
            name='model',
            field=models.CharField(choices=[('Toyota Prado', (('Prado Tx', 'Prado Tx'), ('Toyota LandCruiser', 'Toyota LandCruiser'))), ('RANGE ROVER', (('RANGE ROVER SPORT', 'RANGE ROVER SPORT'), ('RANGE ROVER VELAR', 'RANGE ROVER VELAR'), ('RANGE ROVER EVOQUE', 'RANGE ROVER EVOQUE'), ('RANGE ROVER DNA', 'RANGE ROVER DNA'))), ('Mercedes-Benz', (('Mercedes-Benz AMG GT', 'Mercedes-Benz AMG GT'), ('Mercedes-Benz Maybach', 'Mercedes-Benz Maybach'), ('Mercedes-Benz CLS', 'Mercedes-Benz CLS'), ('Mercedes-Benz E CLASS', 'Mercedes-Benz E CLASS')))], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='current_caruser_booking',
            name='carpicked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.Cars_Available'),
        ),
    ]
