# Generated by Django 3.0.5 on 2021-05-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
