# Generated by Django 3.0.5 on 2021-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesg', models.TextField()),
                ('profile', models.ImageField(upload_to='userfeedback_profile')),
                ('email', models.EmailField(max_length=254)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': ' User Posted FeedBack',
            },
        ),
    ]
