# Generated by Django 3.0.5 on 2021-06-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartmentsbase',
        ),
        migrations.DeleteModel(
            name='Client_Booking_ApartmentForm',
        ),
    ]
