# Generated by Django 3.0.5 on 2021-05-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0002_delete_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentsbase',
            name='Beds',
        ),
        migrations.RemoveField(
            model_name='apartmentsbase',
            name='Category',
        ),
    ]
