# Generated by Django 3.0.5 on 2021-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0002_sendmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='Teamphotos')),
                ('position', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dates', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': ' Umar Safaris Team',
            },
        ),
    ]
