# Generated by Django 3.0.5 on 2021-06-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0002_auto_20210602_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carfeatures',
        ),
        migrations.DeleteModel(
            name='Current_user_booking',
        ),
    ]
