# Generated by Django 3.0.5 on 2021-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0003_auto_20210603_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesOnHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_in_Home', models.ImageField(upload_to='safarisapp/images/gallery/fulls')),
            ],
            options={
                'verbose_name_plural': 'Images and Information on the first page',
            },
        ),
    ]
