# Generated by Django 3.0.5 on 2021-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0003_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Booking_ApartmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ID_No', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Tel', models.IntegerField(default='0000000000')),
            ],
            options={
                'verbose_name_plural': 'Booked Apartments By Clients',
            },
        ),
    ]
