# Generated by Django 3.0.5 on 2021-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0004_imagesonhome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesonhome',
            old_name='Image_in_Home',
            new_name='imghome',
        ),
        migrations.AddField(
            model_name='imagesonhome',
            name='psg',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='imagesonhome',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
