# Generated by Django 3.0.5 on 2021-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0005_auto_20210526_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_booking_apartmentform',
            name='Tel',
            field=models.PositiveIntegerField(),
        ),
    ]
