# Generated by Django 3.0.5 on 2021-05-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisapp', '0006_auto_20210526_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_booking_apartmentform',
            name='Apartments_Available',
            field=models.CharField(choices=[('DEL', 'D1'), ('Rook', 'R1'), ('Bishop', 'B1'), ('Castle', 'C1')], default='Available', max_length=10),
        ),
    ]
